# Generated by Django 5.2.14 on 2026-05-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('set', 'Наборы-конструкторы'), ('tablet', 'Планшеты'), ('stand', 'Подставки')], max_length=20, unique=True, verbose_name='Тип')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ('type',),
            },
        ),
    ]
