# Generated by Django 5.2.14 on 2026-05-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('category', models.CharField(choices=[('transport', 'Транспорт'), ('rent', 'Аренда'), ('equipment', 'Оборудование / конструкторы'), ('marketing', 'Реклама'), ('supplies', 'Расходники'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['date', 'category'], name='finance_exp_date_8ba413_idx')],
            },
        ),
    ]
