# Generated by Django 5.2.14 on 2026-05-07 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя ребёнка')),
                ('last_name', models.CharField(max_length=80, verbose_name='Фамилия ребёнка')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('parent_first_name', models.CharField(max_length=80, verbose_name='Имя родителя')),
                ('parent_last_name', models.CharField(blank=True, default='', max_length=80, verbose_name='Фамилия родителя')),
                ('parent_phone', models.CharField(max_length=32, verbose_name='Телефон родителя')),
                ('parent_telegram', models.CharField(blank=True, default='', max_length=120, verbose_name='Telegram родителя')),
                ('parent_vk', models.URLField(blank=True, default='', verbose_name='ВКонтакте родителя')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость месяца')),
                ('is_active', models.BooleanField(default=True, verbose_name='Занимается сейчас')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='centers.center', verbose_name='Центр')),
            ],
            options={
                'verbose_name': 'Ребёнок',
                'verbose_name_plural': 'Дети',
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
