# Generated by Django 5.2.14 on 2026-05-07 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('children', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False, verbose_name='Присутствовал')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='children.child', verbose_name='Ребёнок')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ('lesson__date', 'child__last_name'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('duration_min', models.PositiveIntegerField(default=60, verbose_name='Длительность, мин')),
                ('topic', models.CharField(blank=True, default='', max_length=255, verbose_name='Тема занятия')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание / план')),
                ('conducted', models.BooleanField(default=False, verbose_name='Проведено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='centers.center', verbose_name='Центр')),
                ('children', models.ManyToManyField(related_name='lessons', through='lessons.Attendance', to='children.child', verbose_name='Дети на занятии')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='staff.staff', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ('-date', '-start_time'),
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='lessons.lesson', verbose_name='Занятие'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['center', 'date'], name='lessons_les_center__66b420_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['date'], name='lessons_les_date_63f5f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('lesson', 'child'), name='uniq_attendance_lesson_child'),
        ),
    ]
